version: '2'

services:
  drupal8_apache:
    build:
      context: ./drupal8-apache/7.0/
    image: quay.io/continuouspipe/drupal8-apache-php7:v1.0
    depends_on:
      - php70_apache

  drupal8_solr_4_10:
    build:
      context: ./drupal8-solr/4.10/
    image: quay.io/continuouspipe/drupal8-solr4:v1.0
    depends_on:
      - solr_4_10

  drupal8_solr_6_2:
    build:
      context: ./drupal8-solr/6.2/
    image: quay.io/continuouspipe/drupal8-solr6:v1.0
    depends_on:
      - solr_6_2

  drupal8_varnish:
    build:
      context: ./drupal8-varnish/4.0/
    image: quay.io/continuouspipe/drupal8-varnish4:v1.0
    depends_on:
      - varnish

  ez:
    build:
      context: ./ez/6.x/
    image: quay.io/continuouspipe/ez6-apache-php7:v1.0
    depends_on:
      - php70_apache

  hem:
    build:
      context: ./hem/
    image: quay.io/continuouspipe/hem1:v1.0
    depends_on:
      - ubuntu

  magento2_nginx:
    build:
      context: ./magento2-nginx/fpm-7.0/
    image: quay.io/continuouspipe/magento2-nginx-php7:v1.0
    depends_on:
      - php70_nginx

  magento2_varnish:
    build:
      context: ./magento2-varnish/4.0/
    image: quay.io/continuouspipe/magento2-varnish4:v1.0
    depends_on:
      - varnish

  memcached:
    build:
      context: ./memcached/1.4/
    image: quay.io/continuouspipe/memcached1.4:v1.0
    depends_on:
      - ubuntu

  mongodb34:
    build:
      context: ./mongodb/
      dockerfile: Dockerfile-3.4
    image: quay.io/continuouspipe/mongodb3.4:v1.0
    depends_on:
      - external_mongodb34

  mysql80:
    build:
      context: ./mysql/
      dockerfile: Dockerfile-8.0
    image: quay.io/continuouspipe/mysql8.0:v1.0
    depends_on:
      - external_mysql80

  mysql57:
    build:
      context: ./mysql/
      dockerfile: Dockerfile-5.7
    image: quay.io/continuouspipe/mysql5.7:v1.0
    depends_on:
      - external_mysql57

  mysql56:
    build:
      context: ./mysql/
      dockerfile: Dockerfile-5.6
    image: quay.io/continuouspipe/mysql5.6:v1.0
    depends_on:
      - external_mysql56

  nodejs:
    build:
      context: ./nodejs/6.0/
    image: quay.io/continuouspipe/nodejs6:v1.0
    depends_on:
      - ubuntu

  php71_apache:
    build:
      context: ./php-apache/
      args:
        PHP_VERSION: 7.1
    image: quay.io/continuouspipe/php7.1-apache:v1.0
    depends_on:
      - ubuntu

  php70_apache:
    build:
      context: ./php-apache/
      args:
        PHP_VERSION: 7.0
    image: quay.io/continuouspipe/php7-apache:v1.0
    depends_on:
      - ubuntu

  php56_apache:
    build:
      context: ./php-apache/
      args:
        PHP_VERSION: 5.6
    image: quay.io/continuouspipe/php5.6-apache:v1.0
    depends_on:
      - ubuntu

  php71_nginx:
    build:
      context: ./php-nginx/
      args:
        PHP_VERSION: 7.1
    image: quay.io/continuouspipe/php7.1-nginx:v1.0
    depends_on:
      - ubuntu

  php70_nginx:
    build:
      context: ./php-nginx/
      args:
        PHP_VERSION: 7.0
    image: quay.io/continuouspipe/php7-nginx:v1.0
    depends_on:
      - ubuntu

  php56_nginx:
    build:
      context: ./php-nginx/
      args:
        PHP_VERSION: 5.6
    image: quay.io/continuouspipe/php5.6-nginx:v1.0
    depends_on:
      - ubuntu
      
  scala_sbt:
    build:
      context: ./scala-base/1.0/
    image: quay.io/continuouspipe/scala-base:1.0
    depends_on:
      - ubuntu

  redis:
    build:
      context: ./redis/3.2/
    image: quay.io/continuouspipe/redis3:v1.0
    depends_on:
      - external_redis

  solr_4_10:
    build:
      context: ./solr/4.10/
    image: quay.io/continuouspipe/solr4:v1.0
    depends_on:
      - external_solr_4_10

  solr_6_2:
    build:
      context: ./solr/6.2/
    image: quay.io/continuouspipe/solr6:v1.0
    depends_on:
      - external_solr_6_2

  symfony_php71_nginx:
    build:
      context: ./symfony/
      dockerfile: Dockerfile-php7.1-nginx
    image: quay.io/continuouspipe/symfony-php7.1-nginx:v1.0
    depends_on:
      - php71_nginx

  symfony_php70_nginx:
    build:
      context: ./symfony/
      dockerfile: Dockerfile-php7-nginx
    image: quay.io/continuouspipe/symfony-php7-nginx:v1.0
    depends_on:
      - php70_nginx

  symfony_php56_nginx:
    build:
      context: ./symfony/
      dockerfile: Dockerfile-php5.6-nginx
    image: quay.io/continuouspipe/symfony-php5.6-nginx:v1.0
    depends_on:
      - php56_nginx

  symfony_php71_apache:
    build:
      context: ./symfony/
      dockerfile: Dockerfile-php7.1-apache
    image: quay.io/continuouspipe/symfony-php7.1-apache:v1.0
    depends_on:
      - php71_apache

  symfony_php70_apache:
    build:
      context: ./symfony/
      dockerfile: Dockerfile-php7-apache
    image: quay.io/continuouspipe/symfony-php7-apache:v1.0
    depends_on:
      - php70_apache

  symfony_php56_apache:
    build:
      context: ./symfony/
      dockerfile: Dockerfile-php5.6-apache
    image: quay.io/continuouspipe/symfony-php5.6-apache:v1.0
    depends_on:
      - php56_apache

  ubuntu:
    build:
      context: ./ubuntu/16.04/
    image: quay.io/continuouspipe/ubuntu16.04:v1.0
    depends_on:
      - external_ubuntu

  varnish:
    build:
      context: ./varnish/4.0/
    image: quay.io/continuouspipe/varnish4:v1.0
    depends_on:
      - ubuntu

  external_mongodb34:
    image: mongo:3.4

  external_mysql80:
    image: mysql:8.0

  external_mysql57:
    image: mysql:5.7

  external_mysql56:
    image: mysql:5.6

  external_redis:
    image: redis:3.2

  external_solr_4_10:
    image: makuk66/docker-solr:4.10.4

  external_solr_6_2:
    image: solr:6.2

  external_ubuntu:
    image: ubuntu:16.04
